go:
  version: 1.13
  cgo: false
repository:
    path: github.com/treydock/ssh_exporter
build:
    binaries:
        - name: ssh_exporter
          path: .
    flags: -a -tags netgo
    ldflags: |
        -extldflags "-static"
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - LICENSE
        - CHANGELOG.md
crossbuild:
    platforms:
        - linux/amd64
        - linux/386
        - linux/arm
        - linux/arm64
        - linux/mips
        - linux/mipsle
        - linux/mips64
        - linux/mips64le
        - linux/ppc64le
